require: rubocop-rspec

AllCops:
  # Include gemspec and Rakefile
  TargetRubyVersion: 2.6
  Include:
    - '**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'Guardfile'

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 8

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 80

# Respect RubyMine formatter
Layout/CaseIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/DotPosition:
  EnforcedStyle: trailing

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

# Name reduce block params |a, e|.
Style/SingleLineBlockParams:
  Enabled: false

# Respect RubyMine formatter
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

# Cannot deal with AR#eager_load
Style/SymbolProc:
  Enabled: false

# Final newline missing.
Layout/TrailingEmptyLines:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

# Do not prefix writer method names with set_
Naming/AccessorMethodName:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false
